name: Hello Spring Boot App to k8s

on:
  workflow_dispatch:
  push:
    # branches:
    #     - main
    # paths:
    #     - "docker/app1-hello/springboot/hello-spring"

jobs:
    build-test:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout Code
            uses: actions/checkout@v4

          - name: Setup JDK
            uses: actions/setup-java@v5
            with:
                distribution: 'temurin' # See 'Supported distributions' for available options
                java-version: '21'

          - name: Build and Test (Maven)
            working-directory: docker/app1-hello/springboot/hello-spring
            run: mvn -B clean verify

          - name: Upload Test Reports
            uses: actions/upload-artifact@v4
            with:
                name: test-reports
                path: docker/app1-hello/springboot/hello-spring/target/surefire-reports

    docker-build-push:
        runs-on: ubuntu-latest
        needs: build-test

        steps:
          - name: Checkout Code
            uses: actions/checkout@v4

          - name: Setup JDK
            uses: actions/setup-java@v5
            with:
                distribution: 'temurin' # See 'Supported distributions' for available options
                java-version: '21'

          - name: Build JAR for Docker
            working-directory: docker/app1-hello/springboot/hello-spring
            run: mvn -B clean package -DskipTests

          - name: Login to DockerHub
            uses: docker/login-action@v3
            with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}   
            
          - name: Build and Push Docker Image
            uses: docker/build-push-action@v6
            with:
                context: docker/app1-hello/springboot/hello-spring
                push: true
                tags: |
                    ${{ secrets.DOCKER_USERNAME }}/hello-spring:latest   
                    ${{ secrets.DOCKER_USERNAME }}/hello-spring:${{ github.sha }}    
                    ${{ secrets.DOCKER_USERNAME }}/hello-spring:${{ github.ref_name }}            


    deploy-local-k8s:
        runs-on: ubuntu-latest
        needs: docker-build-push    
        
        steps:
          - name: Checkout Code
            uses: actions/checkout@v4

          - name: Setup kubectl
            uses: azure/setup-kubectl@v4
            
          - name: Configure kubectl
            run: |
                mkdir -p ~/.kube
                echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config
          
    
          - name: Deploy to Local Kubernetes
            run: kubectl apply -f k8s/local/app1-hello              